################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
O_SRCS += \
../examples/rime/obj_sky/abc.o \
../examples/rime/obj_sky/al_mmac.o \
../examples/rime/obj_sky/announcement.o \
../examples/rime/obj_sky/autostart.o \
../examples/rime/obj_sky/battery-sensor.o \
../examples/rime/obj_sky/broadcast-announcement.o \
../examples/rime/obj_sky/broadcast.o \
../examples/rime/obj_sky/button-sensor.o \
../examples/rime/obj_sky/cc2420-aes.o \
../examples/rime/obj_sky/cc2420-arch-sfd.o \
../examples/rime/obj_sky/cc2420-arch.o \
../examples/rime/obj_sky/cc2420.o \
../examples/rime/obj_sky/cfs-coffee.o \
../examples/rime/obj_sky/chameleon-bitopt.o \
../examples/rime/obj_sky/chameleon-raw.o \
../examples/rime/obj_sky/chameleon.o \
../examples/rime/obj_sky/channel.o \
../examples/rime/obj_sky/checkpoint-arch.o \
../examples/rime/obj_sky/checkpoint.o \
../examples/rime/obj_sky/clock.o \
../examples/rime/obj_sky/collect-link-estimate.o \
../examples/rime/obj_sky/collect-neighbor.o \
../examples/rime/obj_sky/collect.o \
../examples/rime/obj_sky/compower.o \
../examples/rime/obj_sky/contiki-sky-main.o \
../examples/rime/obj_sky/contiki-sky-platform.o \
../examples/rime/obj_sky/contikimac.o \
../examples/rime/obj_sky/crc16.o \
../examples/rime/obj_sky/csma.o \
../examples/rime/obj_sky/ctimer.o \
../examples/rime/obj_sky/cxmac.o \
../examples/rime/obj_sky/dhcpc.o \
../examples/rime/obj_sky/ds2411.o \
../examples/rime/obj_sky/elfloader-msp430.o \
../examples/rime/obj_sky/elfloader.o \
../examples/rime/obj_sky/energest.o \
../examples/rime/obj_sky/etimer.o \
../examples/rime/obj_sky/flash.o \
../examples/rime/obj_sky/frame802154.o \
../examples/rime/obj_sky/framer-802154.o \
../examples/rime/obj_sky/framer-nullmac.o \
../examples/rime/obj_sky/hc.o \
../examples/rime/obj_sky/i2c.o \
../examples/rime/obj_sky/ifft.o \
../examples/rime/obj_sky/ipolite.o \
../examples/rime/obj_sky/leds-arch.o \
../examples/rime/obj_sky/leds.o \
../examples/rime/obj_sky/light-sensor.o \
../examples/rime/obj_sky/list.o \
../examples/rime/obj_sky/lpm.o \
../examples/rime/obj_sky/lpp.o \
../examples/rime/obj_sky/mac.o \
../examples/rime/obj_sky/me.o \
../examples/rime/obj_sky/me_tabs.o \
../examples/rime/obj_sky/memb.o \
../examples/rime/obj_sky/mesh.o \
../examples/rime/obj_sky/mmem.o \
../examples/rime/obj_sky/msp430.o \
../examples/rime/obj_sky/mt.o \
../examples/rime/obj_sky/mtarch.o \
../examples/rime/obj_sky/multihop.o \
../examples/rime/obj_sky/neighbor-discovery.o \
../examples/rime/obj_sky/netflood.o \
../examples/rime/obj_sky/netstack.o \
../examples/rime/obj_sky/node-id.o \
../examples/rime/obj_sky/nullmac.o \
../examples/rime/obj_sky/nullradio.o \
../examples/rime/obj_sky/nullrdc-noframer.o \
../examples/rime/obj_sky/nullrdc.o \
../examples/rime/obj_sky/packetbuf.o \
../examples/rime/obj_sky/packetqueue.o \
../examples/rime/obj_sky/phase.o \
../examples/rime/obj_sky/polite-announcement.o \
../examples/rime/obj_sky/polite.o \
../examples/rime/obj_sky/print-stats.o \
../examples/rime/obj_sky/process.o \
../examples/rime/obj_sky/procinit.o \
../examples/rime/obj_sky/profile.o \
../examples/rime/obj_sky/psock.o \
../examples/rime/obj_sky/queuebuf.o \
../examples/rime/obj_sky/radio-sensor.o \
../examples/rime/obj_sky/random.o \
../examples/rime/obj_sky/resolv.o \
../examples/rime/obj_sky/rime.o \
../examples/rime/obj_sky/rimeaddr.o \
../examples/rime/obj_sky/rimestats.o \
../examples/rime/obj_sky/ringbuf.o \
../examples/rime/obj_sky/rmh.o \
../examples/rime/obj_sky/route-discovery.o \
../examples/rime/obj_sky/route.o \
../examples/rime/obj_sky/rtimer-arch.o \
../examples/rime/obj_sky/rtimer.o \
../examples/rime/obj_sky/rucb.o \
../examples/rime/obj_sky/rudolph0.o \
../examples/rime/obj_sky/rudolph1.o \
../examples/rime/obj_sky/rudolph2.o \
../examples/rime/obj_sky/runicast.o \
../examples/rime/obj_sky/sensors.o \
../examples/rime/obj_sky/serial-line.o \
../examples/rime/obj_sky/sht11-sensor.o \
../examples/rime/obj_sky/sht11.o \
../examples/rime/obj_sky/sicslowmac.o \
../examples/rime/obj_sky/sky-sensors.o \
../examples/rime/obj_sky/slip.o \
../examples/rime/obj_sky/slip_uart1.o \
../examples/rime/obj_sky/spi.o \
../examples/rime/obj_sky/stbroadcast.o \
../examples/rime/obj_sky/stimer.o \
../examples/rime/obj_sky/stunicast.o \
../examples/rime/obj_sky/symbols.o \
../examples/rime/obj_sky/symtab.o \
../examples/rime/obj_sky/tcpdump.o \
../examples/rime/obj_sky/tcpip.o \
../examples/rime/obj_sky/timer.o \
../examples/rime/obj_sky/timesynch.o \
../examples/rime/obj_sky/timetable-aggregate.o \
../examples/rime/obj_sky/timetable.o \
../examples/rime/obj_sky/trickle.o \
../examples/rime/obj_sky/uaodv-rt.o \
../examples/rime/obj_sky/uaodv.o \
../examples/rime/obj_sky/uart1-putchar.o \
../examples/rime/obj_sky/uart1.o \
../examples/rime/obj_sky/uip-debug.o \
../examples/rime/obj_sky/uip-fw-drv.o \
../examples/rime/obj_sky/uip-fw.o \
../examples/rime/obj_sky/uip-ipchksum.o \
../examples/rime/obj_sky/uip-neighbor.o \
../examples/rime/obj_sky/uip-over-mesh.o \
../examples/rime/obj_sky/uip-split.o \
../examples/rime/obj_sky/uip-udp-packet.o \
../examples/rime/obj_sky/uip.o \
../examples/rime/obj_sky/uip_arp.o \
../examples/rime/obj_sky/uiplib.o \
../examples/rime/obj_sky/unicast.o \
../examples/rime/obj_sky/watchdog.o \
../examples/rime/obj_sky/xmac.o \
../examples/rime/obj_sky/xmem.o 


# Each subdirectory must supply rules for building sources it contributes

